import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';

import { CoreLayout, Providers } from '@/components/layout';
import { env } from '@/utils/env';
import { generateOpenGraph } from '@/utils/seo';

import { APP_NAME } from '@app/constants';

import './globals.scss';

const mainFont = Inter({
  subsets: ['latin', 'cyrillic'],
});

/**
 * Generic application`s metadata generation.
 */
export async function generateMetadata(): Promise<Metadata> {
  const CANONICAL_URL = env.CANONICAL_URL;

  return {
    metadataBase: new URL(CANONICAL_URL),
    title: {
      template: `%s | ${APP_NAME}`,
      default: APP_NAME,
    },
    description: 'Generated by create next app',
    appleWebApp: {
      title: APP_NAME,
      capable: false,
    },
    alternates: {
      canonical: CANONICAL_URL,
      languages: {
        // ru: CANONICAL_URL,

        // Should be changed to another one, if i18n has been implemented
        'x-default': CANONICAL_URL,
      },
    },
    openGraph: generateOpenGraph({
      title: 'Main page',
      description: 'This is a main page',
    }),
  };
}

/**
 * Top-level app layout. Contains providers, core layout.
 *
 * @constructor
 * @todo Update next-themes and remove suppressHydrationWarning
 */
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang='ru'
      dir='ltr'
      suppressHydrationWarning
    >
      <body className={mainFont.className}>
        <Providers>
          <CoreLayout>{children}</CoreLayout>
        </Providers>
      </body>
    </html>
  );
}
