name: 'Cypress e2e'
on:
  push:
  pull_request:

jobs:
  e2e:
    strategy:
      matrix:
        NODE_VERSION:
          - '20'

    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: 'Install Node (${{ matrix.NODE_VERSION }})'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.NODE_VERSION }}'

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile

      - name: 'Run Cypress in headless mode'
        run: yarn e2e:ci
